apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: keycloak
type: Opaque
data:
  admin-password: ""