apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: keycloak
automountServiceAccountToken: false